"""cascade_del_try_1

Revision ID: 943e481b903e
Revises: 4c0a3e742094
Create Date: 2024-01-22 19:34:52.959472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943e481b903e'
down_revision: Union[str, None] = '4c0a3e742094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('publication_tag_tag_id_fkey', 'publication_tag', type_='foreignkey')
    op.drop_constraint('publication_tag_publication_id_fkey', 'publication_tag', type_='foreignkey')
    op.create_foreign_key(None, 'publication_tag', 'publications', ['publication_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'publication_tag', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publication_tag', type_='foreignkey')
    op.drop_constraint(None, 'publication_tag', type_='foreignkey')
    op.create_foreign_key('publication_tag_publication_id_fkey', 'publication_tag', 'publications', ['publication_id'], ['id'])
    op.create_foreign_key('publication_tag_tag_id_fkey', 'publication_tag', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
