"""fix_m2m_for_tags

Revision ID: 9815c80bf927
Revises: 495ccdfddc1e
Create Date: 2024-01-15 21:36:09.430942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9815c80bf927'
down_revision: Union[str, None] = '495ccdfddc1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication_tag', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication_tag', 'id')
    # ### end Alembic commands ###
