"""pub_image + user.confirmed

Revision ID: e1270c4a0a3f
Revises: a6a95392be5d
Create Date: 2024-01-13 15:49:43.387959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1270c4a0a3f'
down_revision: Union[str, None] = 'a6a95392be5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pub_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_img', sa.String(length=255), nullable=False),
    sa.Column('updated_img', sa.String(length=255), nullable=True),
    sa.Column('qr_code_img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('publications', sa.Column('pub_image_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'publications', ['pub_image_id'])
    op.create_foreign_key(None, 'publications', 'pub_images', ['pub_image_id'], ['id'])
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    op.drop_constraint(None, 'publications', type_='foreignkey')
    op.drop_constraint(None, 'publications', type_='unique')
    op.drop_column('publications', 'pub_image_id')
    op.drop_table('pub_images')
    # ### end Alembic commands ###
